januaryexpenses=int(input("What is your expense for january"))
feburaryexpenses=int(input("What is your expense for feburary"))
marchexpenses=int(input("What is your expense for march"))
aprilexpenses=int(input("What is your expense for april"))
mayexpenses=int(input("What is your expense for may"))
total=januaryexpenses+feburaryexpenses+marchexpenses+aprilexpenses+mayexpenses
Average=total/5
print("The average expense is"+str(Average))